import { chromium } from "@playwright/test";
const base = "http://localhost:3000";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1300, height: 900 } });
const errors = [];
p.on("pageerror", (e) => errors.push(String(e).slice(0, 300)));
p.on("response", (r) => r.status() >= 500 && errors.push(`http ${r.status()} ${r.url()}`));
await p.goto(base + "/demo");
await p.click("[data-testid=enter-career_advisor]");
await p.waitForURL(/home/, { timeout: 120000 });
await p.screenshot({ path: "/tmp/claude-0/shots/hero1b-home.png" });
await p.goto(base + "/en/cases");
await p.locator("[data-testid=case-row]", { hasText: "Adam Nasser" }).first().locator("a").first().click();
await p.waitForURL(/cases\/.+/);
await p.click("[data-testid=ai-brief]");
await p.locator("[data-testid=ai-brief-result]").waitFor({ timeout: 60000 });
await p.click("[data-testid=draft-plan]");
await p.locator("[data-testid=plan-draft]").waitFor({ timeout: 60000 });
await p.screenshot({ path: "/tmp/claude-0/shots/hero1b-case.png", fullPage: true });
await p.click("[data-testid=approve-plan]");
await p.locator("[data-testid=plan-accepted]").waitFor({ timeout: 60000 });
console.log("plan approved");
// Adam sees tasks
await p.click("[data-testid=persona-switcher]");
await p.click("[data-testid=persona-student]");
await p.waitForURL(/home/, { timeout: 120000 });
await p.goto(base + "/en/tasks");
console.log("adam tasks:", await p.locator("[data-testid=task-row]").count());
await p.screenshot({ path: "/tmp/claude-0/shots/hero1b-adam-tasks.png" });
const reqUrl = (await import("node:fs")).readFileSync("/tmp/claude-0/hero1-url.txt", "utf8").replace("?submitted=1", "");
await p.goto(reqUrl);
console.log("request status:", await p.locator("[data-testid=request-title] + div").textContent());
// Rania got an update
await p.click("[data-testid=persona-switcher]");
await p.click("[data-testid=persona-parent]");
await p.waitForURL(/home/, { timeout: 120000 });
await p.click("[data-testid=notifications-bell]");
await p.waitForTimeout(1500);
await p.screenshot({ path: "/tmp/claude-0/shots/hero1b-rania.png" });
console.log("errors", errors);
await b.close();
