// Generated by scripts/research/assemble.mjs. Official entry requirements, validated against the fetched pages.
import type { OfficialBatch } from "../official";
import cawide from "./cawide.json";
import uae from "./uae.json";
import uk1 from "./uk1.json";
import uk2 from "./uk2.json";
import us from "./us.json";
import world from "./world.json";

export const OFFICIAL_BATCHES: OfficialBatch[] = [cawide as OfficialBatch, uae as OfficialBatch, uk1 as OfficialBatch, uk2 as OfficialBatch, us as OfficialBatch, world as OfficialBatch];
