// Starter university programmes for the pathways module.
//
// ACCURACY: every requirement here is INDICATIVE. None of these pages could be fetched from the build
// environment (outbound access to university sites was blocked), so every programme is seeded with
// indicative = true and lastVerifiedAt = null, and the app shows "not yet checked; confirm with the
// university". Values reflect typical published offers as generally known and change every year.
// Where a figure was not known with reasonable confidence it is left out on purpose, so the checker
// shows "unknown" rather than a guessed number. A counselor marks a programme as checked in the app
// after comparing it with the official page (sourceUrl).
import type { EnglishReq, ProgramRequirements } from "@/server/pathways/types";

type Bi = { en: string; ar: string };
const bi = (en: string, ar: string): Bi => ({ en, ar });

export type ExtraUniversity = { key: string; name: Bi; countryCode: string; city: Bi; website: string; deadlineMonth: number | null; system: string; applyVia: string; programs: string[] };

/** Universities the career catalogue does not have yet. Upserted by key. */
export const EXTRA_UNIVERSITIES: ExtraUniversity[] = [
  { key: "university_of_jordan", name: bi("The University of Jordan", "الجامعة الأردنية"), countryCode: "JO", city: bi("Amman", "عمّان"), website: "ju.edu.jo", deadlineMonth: 8, system: "JO", applyVia: "JORDAN_UNIFIED", programs: ["Medicine", "Law", "Business Administration"] },
  { key: "just", name: bi("Jordan University of Science and Technology", "جامعة العلوم والتكنولوجيا الأردنية"), countryCode: "JO", city: bi("Irbid", "إربد"), website: "just.edu.jo", deadlineMonth: 8, system: "JO", applyVia: "JORDAN_UNIFIED", programs: ["Medicine", "Civil Engineering"] },
  { key: "psut", name: bi("Princess Sumaya University for Technology", "جامعة الأميرة سمية للتكنولوجيا"), countryCode: "JO", city: bi("Amman", "عمّان"), website: "psut.edu.jo", deadlineMonth: 8, system: "JO", applyVia: "DIRECT", programs: ["Computer Science", "Electrical Engineering"] },
  { key: "gju", name: bi("German Jordanian University", "الجامعة الألمانية الأردنية"), countryCode: "JO", city: bi("Madaba", "مادبا"), website: "gju.edu.jo", deadlineMonth: 8, system: "JO", applyVia: "JORDAN_UNIFIED", programs: ["Mechanical Engineering", "Architecture"] },
  { key: "yarmouk", name: bi("Yarmouk University", "جامعة اليرموك"), countryCode: "JO", city: bi("Irbid", "إربد"), website: "yu.edu.jo", deadlineMonth: 8, system: "JO", applyVia: "JORDAN_UNIFIED", programs: ["Computer Science"] },
  { key: "unimelb", name: bi("The University of Melbourne", "جامعة ملبورن"), countryCode: "AU", city: bi("Melbourne", "ملبورن"), website: "unimelb.edu.au", deadlineMonth: null, system: "AU", applyVia: "DIRECT", programs: ["Bachelor of Science", "Bachelor of Design"] },
];

/** Application route and system for universities already in the career catalogue. */
export const UNIVERSITY_ROUTES: Record<string, { system: string; applyVia: string }> = {
  oxford: { system: "UK", applyVia: "UCAS" },
  cambridge: { system: "UK", applyVia: "UCAS" },
  imperial_college_london: { system: "UK", applyVia: "UCAS" },
  ucl: { system: "UK", applyVia: "UCAS" },
  kings_college_london: { system: "UK", applyVia: "UCAS" },
  edinburgh: { system: "UK", applyVia: "UCAS" },
  manchester: { system: "UK", applyVia: "UCAS" },
  lse: { system: "UK", applyVia: "UCAS" },
  warwick: { system: "UK", applyVia: "UCAS" },
  bristol: { system: "UK", applyVia: "UCAS" },
  glasgow: { system: "UK", applyVia: "UCAS" },
  mit: { system: "US", applyVia: "MIT_APP" },
  stanford: { system: "US", applyVia: "COMMON_APP" },
  carnegie_mellon: { system: "US", applyVia: "COMMON_APP" },
  uc_berkeley: { system: "US", applyVia: "UC_APP" },
  university_of_michigan: { system: "US", applyVia: "COMMON_APP" },
  nyu_abu_dhabi: { system: "US", applyVia: "COMMON_APP" },
  khalifa_university: { system: "AE", applyVia: "DIRECT" },
  uae_university: { system: "AE", applyVia: "DIRECT" },
  american_university_sharjah: { system: "AE", applyVia: "DIRECT" },
  university_of_toronto: { system: "CA", applyVia: "OUAC" },
  waterloo: { system: "CA", applyVia: "OUAC" },
  tu_delft: { system: "NL", applyVia: "STUDIELINK" },
  university_of_amsterdam: { system: "NL", applyVia: "STUDIELINK" },
  tu_munich: { system: "DE", applyVia: "DIRECT" },
  trinity_college_dublin: { system: "IE", applyVia: "CAO" },
};

export type ProgramSeed = {
  key: string;
  uni: string;
  name: Bi;
  field: string;
  degree: string;
  years: number;
  required: string[];
  recommended: string[];
  req: ProgramRequirements;
  english: EnglishReq | null;
  notes?: Bi;
  source: string;
};

const UCAS_OXBRIDGE = { via: "UCAS" as const, deadlines: [{ kind: "oxbridge" as const, month: 10, day: 15 }], url: "https://www.ucas.com" };
const UCAS_MAIN = { via: "UCAS" as const, deadlines: [{ kind: "equal" as const, month: 1, day: 14 }], url: "https://www.ucas.com" };
const JORDAN_ROUTE = { via: "JORDAN_UNIFIED" as const, deadlines: [{ kind: "unified" as const, month: 8, day: 15 }], url: "https://admhec.gov.jo" };
const JORDAN_NOTE = bi(
  "For Jordanian students, places are allocated through the unified admission process, and the real cut-off averages change every year and are usually well above the minimum. Students with British, IB or American certificates need an equivalency from the Ministry of Education. Jordan is also moving to a new field-based Tawjihi, so confirm which fields are eligible.",
  "يُقبل الطلبة الأردنيون عبر القبول الموحد، ومعدلات القبول الفعلية تتغير كل عام وتكون عادة أعلى بكثير من الحد الأدنى. ويحتاج حملة الشهادات البريطانية أو الدولية أو الأمريكية إلى معادلة من وزارة التربية والتعليم. كما ينتقل الأردن إلى نظام توجيهي جديد قائم على الحقول، لذا تأكد من الحقول المقبولة.",
);

export const PROGRAMS: ProgramSeed[] = [
  // ---------------- United Kingdom ----------------
  {
    key: "ucl-computer-science-bsc",
    uni: "ucl",
    name: bi("Computer Science BSc", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 3,
    required: ["MATH"],
    recommended: ["FURTHER_MATH"],
    req: {
      route: UCAS_MAIN,
      BRITISH: { grades: "A*A*A", subjects: [{ code: "MATH", min: "A*" }] },
      IB: { points: 40, hl: [{ code: "MATH", min: "7" }] },
      AMERICAN: { testPolicy: "REQUIRED", ap: [{ code: "MATH", min: "5" }], notesEn: "US high school diploma plus APs or SAT/ACT; check the UCL country page for the exact combination.", notesAr: "شهادة الثانوية الأمريكية مع مواد AP أو اختبار SAT أو ACT، راجع صفحة الدولة في موقع الجامعة لمعرفة التركيبة المطلوبة." },
    },
    english: { ielts: 6.5, ieltsMinBand: 6.0, toefl: 92 },
    source: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/computer-science-bsc",
  },
  {
    key: "imperial-computing-beng",
    uni: "imperial_college_london",
    name: bi("Computing BEng", "بكالوريوس هندسة الحوسبة"),
    field: "computer_science",
    degree: "BEng",
    years: 3,
    required: ["MATH"],
    recommended: ["FURTHER_MATH", "PHYS"],
    req: {
      route: UCAS_MAIN,
      admissionsTests: ["TMUA"],
      BRITISH: { grades: "A*A*A", subjects: [{ code: "MATH", min: "A*" }] },
      IB: { points: 40, hl: [{ code: "MATH", min: "7" }] },
    },
    english: { ielts: 6.5, ieltsMinBand: 6.0 },
    notes: bi("Offers can depend on the TMUA result.", "قد يعتمد العرض على نتيجة اختبار TMUA."),
    source: "https://www.imperial.ac.uk/study/courses/undergraduate/computing-beng/",
  },
  {
    key: "cambridge-computer-science-ba",
    uni: "cambridge",
    name: bi("Computer Science BA", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BA",
    years: 3,
    required: ["MATH"],
    recommended: ["FURTHER_MATH", "PHYS"],
    req: {
      route: UCAS_OXBRIDGE,
      admissionsTests: ["TMUA"],
      BRITISH: { grades: "A*A*A", subjects: [{ code: "MATH", min: "A*" }] },
      IB: { points: 40, hl: [{ code: "MATH", min: "7" }] },
    },
    english: { ielts: 7.5, ieltsMinBand: 7.0, toefl: 110 },
    notes: bi("Most colleges ask for A-level Further Mathematics when the school offers it.", "تطلب معظم الكليات مادة الرياضيات الإضافية في A-level إذا كانت المدرسة تقدمها."),
    source: "https://www.undergraduate.study.cam.ac.uk/courses/computer-science",
  },
  {
    key: "oxford-medicine-bmbch",
    uni: "oxford",
    name: bi("Medicine BM BCh", "بكالوريوس الطب والجراحة"),
    field: "medicine",
    degree: "BMBCh",
    years: 6,
    required: ["CHEM"],
    recommended: ["BIO", "PHYS", "MATH"],
    req: {
      route: UCAS_OXBRIDGE,
      admissionsTests: ["UCAT"],
      BRITISH: { grades: "A*AA", subjects: [{ code: "CHEM", min: "A" }], notesEn: "Chemistry plus at least one of Biology, Physics or Mathematics.", notesAr: "الكيمياء إضافة إلى مادة واحدة على الأقل من الأحياء أو الفيزياء أو الرياضيات." },
      IB: { points: 39, hl: [{ code: "CHEM", min: "6" }] },
    },
    english: { ielts: 7.5, ieltsMinBand: 7.0, toefl: 110 },
    source: "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/medicine",
  },
  {
    key: "manchester-medicine-mbchb",
    uni: "manchester",
    name: bi("Medicine MBChB", "بكالوريوس الطب والجراحة"),
    field: "medicine",
    degree: "MBChB",
    years: 5,
    required: ["CHEM", "BIO"],
    recommended: [],
    req: {
      route: { ...UCAS_OXBRIDGE, deadlines: [{ kind: "oxbridge", month: 10, day: 15 }] },
      admissionsTests: ["UCAT"],
      BRITISH: { grades: "AAA", notesEn: "Chemistry or Biology and at least one other science.", notesAr: "الكيمياء أو الأحياء ومادة علمية أخرى على الأقل." },
      IB: { points: 36 },
    },
    english: { ielts: 7.0, ieltsMinBand: 7.0 },
    notes: bi("Medicine applications close on the early UCAS date in October.", "يُغلق التقديم لدراسة الطب في موعد UCAS المبكر في أكتوبر."),
    source: "https://www.manchester.ac.uk/study/undergraduate/courses/2026/01428/mbchb-medicine/",
  },
  {
    key: "lse-economics-bsc",
    uni: "lse",
    name: bi("Economics BSc", "بكالوريوس الاقتصاد"),
    field: "economics",
    degree: "BSc",
    years: 3,
    required: ["MATH"],
    recommended: ["FURTHER_MATH"],
    req: {
      route: UCAS_MAIN,
      BRITISH: { grades: "A*AA", subjects: [{ code: "MATH", min: "A*" }] },
      IB: { points: 38, hl: [{ code: "MATH", min: "7" }] },
    },
    english: { ielts: 7.0, ieltsMinBand: 7.0, toefl: 100 },
    source: "https://www.lse.ac.uk/study-at-lse/undergraduate/bsc-economics",
  },
  {
    key: "kcl-law-llb",
    uni: "kings_college_london",
    name: bi("Law LLB", "بكالوريوس القانون"),
    field: "law",
    degree: "LLB",
    years: 3,
    required: [],
    recommended: ["HIST", "ENG_LIT"],
    req: {
      route: UCAS_MAIN,
      admissionsTests: ["LNAT"],
      BRITISH: { grades: "A*AA" },
      IB: { points: 35 },
    },
    english: { ielts: 7.5, ieltsMinBand: 7.0 },
    source: "https://www.kcl.ac.uk/study/undergraduate/courses/law-llb",
  },
  {
    key: "ucl-psychology-bsc",
    uni: "ucl",
    name: bi("Psychology BSc", "بكالوريوس علم النفس"),
    field: "psychology",
    degree: "BSc",
    years: 3,
    required: [],
    recommended: ["BIO", "MATH", "PSY"],
    req: { route: UCAS_MAIN, BRITISH: { grades: "A*AA" }, IB: { points: 39 } },
    english: { ielts: 7.0, ieltsMinBand: 6.5 },
    source: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/psychology-bsc",
  },
  {
    key: "ucl-architecture-bsc",
    uni: "ucl",
    name: bi("Architecture BSc", "بكالوريوس العمارة"),
    field: "architecture",
    degree: "BSc",
    years: 3,
    required: [],
    recommended: ["ART", "MATH", "PHYS"],
    req: { route: UCAS_MAIN, BRITISH: { grades: "AAA" }, IB: { points: 38 } },
    english: { ielts: 7.0, ieltsMinBand: 6.5 },
    notes: bi("A portfolio is part of the application.", "يُطلب ملف أعمال فنية ضمن الطلب."),
    source: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/architecture-bsc",
  },
  {
    key: "imperial-mechanical-engineering-meng",
    uni: "imperial_college_london",
    name: bi("Mechanical Engineering MEng", "ماجستير متكامل في الهندسة الميكانيكية"),
    field: "engineering",
    degree: "MEng",
    years: 4,
    required: ["MATH", "PHYS"],
    recommended: ["FURTHER_MATH"],
    req: {
      route: UCAS_MAIN,
      BRITISH: { grades: "A*A*A", subjects: [{ code: "MATH", min: "A*" }, { code: "PHYS", min: "A" }] },
      IB: { points: 40, hl: [{ code: "MATH", min: "7" }, { code: "PHYS", min: "6" }] },
    },
    english: { ielts: 6.5, ieltsMinBand: 6.0 },
    source: "https://www.imperial.ac.uk/study/courses/undergraduate/mechanical-engineering/",
  },
  {
    key: "warwick-management-bsc",
    uni: "warwick",
    name: bi("Management BSc", "بكالوريوس الإدارة"),
    field: "business",
    degree: "BSc",
    years: 3,
    required: [],
    recommended: ["MATH", "ECON"],
    req: { route: UCAS_MAIN, BRITISH: { grades: "A*AA" }, IB: { points: 38 } },
    english: { ielts: 7.0, ieltsMinBand: 6.5 },
    source: "https://warwick.ac.uk/study/undergraduate/courses/management",
  },

  // ---------------- United States ----------------
  {
    key: "mit-computer-science-sb",
    uni: "mit",
    name: bi("Computer Science and Engineering (Course 6-3)", "علوم وهندسة الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH", "PHYS"],
    recommended: ["CHEM", "BIO"],
    req: {
      route: { via: "MIT_APP", deadlines: [{ kind: "early", month: 11, day: 1 }, { kind: "regular", month: 1, day: 5 }], url: "https://mitadmissions.org/apply/" },
      AMERICAN: { testPolicy: "REQUIRED", notesEn: "MIT admits to the institute, not to a major. Calculus and calculus-based physics are expected.", notesAr: "يقبل المعهد الطلاب في المعهد لا في تخصص محدد، ويُتوقع دراسة التفاضل والتكامل والفيزياء المعتمدة عليه." },
      BRITISH: { notesEn: "A-levels are accepted; there is no published grade profile.", notesAr: "تُقبل شهادات A-level ولا يوجد ملف درجات منشور." },
      IB: { notesEn: "The IB Diploma is accepted; there is no published points minimum.", notesAr: "تُقبل الدبلومة الدولية ولا يوجد حد أدنى منشور للنقاط." },
    },
    english: { ielts: 7.0, toefl: 90, notesEn: "Recommended: IELTS 7.5 or TOEFL 100.", notesAr: "المستحسن: IELTS 7.5 أو TOEFL 100." },
    source: "https://mitadmissions.org/apply/firstyear/",
  },
  {
    key: "stanford-computer-science-bs",
    uni: "stanford",
    name: bi("Computer Science BS", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH"],
    recommended: ["PHYS", "CS"],
    req: {
      route: { via: "COMMON_APP", deadlines: [{ kind: "early", month: 11, day: 1 }, { kind: "regular", month: 1, day: 5 }], url: "https://admission.stanford.edu/apply/" },
      AMERICAN: { testPolicy: "REQUIRED", notesEn: "Check the current testing policy on the admission site before applying.", notesAr: "تحقق من سياسة الاختبارات الحالية في موقع القبول قبل التقديم." },
    },
    english: null,
    source: "https://admission.stanford.edu/apply/first-year/",
  },
  {
    key: "cmu-computer-science-bs",
    uni: "carnegie_mellon",
    name: bi("Computer Science BS", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH"],
    recommended: ["PHYS", "CHEM"],
    req: {
      route: { via: "COMMON_APP", deadlines: [{ kind: "early", month: 11, day: 1 }, { kind: "regular", month: 1, day: 3 }], url: "https://admission.enrollment.cmu.edu/" },
      AMERICAN: { testPolicy: "REQUIRED", ap: [{ code: "MATH" }] },
    },
    english: { ielts: 7.5, toefl: 102 },
    source: "https://admission.enrollment.cmu.edu/pages/applying",
  },
  {
    key: "berkeley-eecs-bs",
    uni: "uc_berkeley",
    name: bi("Electrical Engineering and Computer Sciences BS", "بكالوريوس الهندسة الكهربائية وعلوم الحاسوب"),
    field: "engineering",
    degree: "BSc",
    years: 4,
    required: ["MATH"],
    recommended: ["PHYS", "CHEM"],
    req: {
      route: { via: "UC_APP", deadlines: [{ kind: "regular", month: 11, day: 30 }], url: "https://apply.universityofcalifornia.edu/" },
      AMERICAN: { gpa: 3.4, testPolicy: "BLIND", notesEn: "The University of California does not consider SAT or ACT scores. 3.4 is the minimum UC GPA for non-residents; admitted students are far higher.", notesAr: "لا تنظر جامعة كاليفورنيا في درجات SAT أو ACT. المعدل 3.4 هو الحد الأدنى لغير المقيمين، ومعدلات المقبولين أعلى بكثير." },
    },
    english: { ielts: 6.5, toefl: 80 },
    source: "https://admissions.berkeley.edu/apply-to-berkeley/",
  },
  {
    key: "umich-engineering-bse",
    uni: "university_of_michigan",
    name: bi("Engineering BSE", "بكالوريوس الهندسة"),
    field: "engineering",
    degree: "BSc",
    years: 4,
    required: ["MATH", "PHYS", "CHEM"],
    recommended: [],
    req: {
      route: { via: "COMMON_APP", deadlines: [{ kind: "early", month: 11, day: 1 }, { kind: "regular", month: 2, day: 1 }], url: "https://admissions.umich.edu/apply" },
      AMERICAN: { testPolicy: "OPTIONAL" },
    },
    english: null,
    source: "https://admissions.umich.edu/apply/first-year-applicants",
  },
  {
    key: "nyuad-computer-science-bs",
    uni: "nyu_abu_dhabi",
    name: bi("Computer Science BS", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH"],
    recommended: [],
    req: {
      route: { via: "COMMON_APP", deadlines: [{ kind: "early", month: 11, day: 1 }, { kind: "regular", month: 1, day: 5 }], url: "https://nyuad.nyu.edu/en/admissions.html" },
      AMERICAN: { testPolicy: "OPTIONAL" },
    },
    english: null,
    notes: bi("Candidates may be invited to a Candidate Weekend.", "قد يُدعى المتقدمون إلى عطلة نهاية أسبوع للمرشحين."),
    source: "https://nyuad.nyu.edu/en/admissions/undergraduate.html",
  },

  // ---------------- United Arab Emirates ----------------
  {
    key: "ku-computer-science-bsc",
    uni: "khalifa_university",
    name: bi("Computer Science BSc", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH", "PHYS"],
    recommended: [],
    req: {
      route: { via: "DIRECT", url: "https://www.ku.ac.ae/admissions" },
      UAE_MOE: { streams: ["ADVANCED", "ELITE"], emsat: [{ kind: "EMSAT_MATH" }, { kind: "EMSAT_PHYSICS" }], notesEn: "EmSAT Mathematics and Physics are part of the application; minimum scores are set each year.", notesAr: "يُطلب اختبار EmSAT في الرياضيات والفيزياء، وتُحدَّد الدرجات الدنيا كل عام." },
    },
    english: { notesEn: "EmSAT English, IELTS or TOEFL; confirm the current minimum with the university.", notesAr: "EmSAT للغة الإنجليزية أو IELTS أو TOEFL، تأكد من الحد الأدنى الحالي مع الجامعة." },
    source: "https://www.ku.ac.ae/admissions",
  },
  {
    key: "uaeu-medicine-md",
    uni: "uae_university",
    name: bi("Doctor of Medicine (MD)", "دكتور في الطب"),
    field: "medicine",
    degree: "MD",
    years: 6,
    required: ["CHEM", "BIO"],
    recommended: ["PHYS"],
    req: {
      route: { via: "DIRECT", url: "https://www.uaeu.ac.ae/en/admission/" },
      UAE_MOE: { streams: ["ADVANCED", "ELITE"], notesEn: "High school average and EmSAT minimums are set each admission cycle.", notesAr: "يُحدَّد المعدل والحد الأدنى لاختبارات EmSAT في كل دورة قبول." },
    },
    english: null,
    source: "https://www.uaeu.ac.ae/en/admission/",
  },
  {
    key: "aus-architecture-barch",
    uni: "american_university_sharjah",
    name: bi("Bachelor of Architecture", "بكالوريوس العمارة"),
    field: "architecture",
    degree: "BArch",
    years: 5,
    required: [],
    recommended: ["ART", "MATH"],
    req: { route: { via: "DIRECT", url: "https://www.aus.edu/admissions" }, AMERICAN: { testPolicy: "OPTIONAL" } },
    english: { ielts: 6.5, toefl: 80 },
    source: "https://www.aus.edu/admissions",
  },

  // ---------------- Jordan ----------------
  {
    key: "ju-medicine-md",
    uni: "university_of_jordan",
    name: bi("Doctor of Medicine", "دكتور في الطب"),
    field: "medicine",
    degree: "MD",
    years: 6,
    required: ["CHEM", "BIO"],
    recommended: [],
    req: { route: JORDAN_ROUTE, JORDAN_TAWJIHI: { average: 85, streams: ["SCIENTIFIC"], notesEn: "85% is the national minimum for medicine; the competitive cut-off is much higher.", notesAr: "85% هو الحد الأدنى الوطني لدراسة الطب، أما معدل القبول التنافسي فأعلى بكثير." } },
    english: null,
    notes: JORDAN_NOTE,
    source: "https://ju.edu.jo",
  },
  {
    key: "ju-law-llb",
    uni: "university_of_jordan",
    name: bi("Law LLB", "بكالوريوس القانون"),
    field: "law",
    degree: "LLB",
    years: 4,
    required: [],
    recommended: [],
    req: { route: JORDAN_ROUTE, JORDAN_TAWJIHI: { streams: ["SCIENTIFIC", "LITERARY"] } },
    english: null,
    notes: JORDAN_NOTE,
    source: "https://ju.edu.jo",
  },
  {
    key: "ju-business-administration-bba",
    uni: "university_of_jordan",
    name: bi("Business Administration", "بكالوريوس إدارة الأعمال"),
    field: "business",
    degree: "BBA",
    years: 4,
    required: [],
    recommended: ["MATH"],
    req: { route: JORDAN_ROUTE, JORDAN_TAWJIHI: { streams: ["SCIENTIFIC", "LITERARY", "IT"] } },
    english: null,
    notes: JORDAN_NOTE,
    source: "https://ju.edu.jo",
  },
  {
    key: "just-medicine-md",
    uni: "just",
    name: bi("Doctor of Medicine", "دكتور في الطب"),
    field: "medicine",
    degree: "MD",
    years: 6,
    required: ["CHEM", "BIO"],
    recommended: [],
    req: { route: JORDAN_ROUTE, JORDAN_TAWJIHI: { average: 85, streams: ["SCIENTIFIC"] } },
    english: null,
    notes: JORDAN_NOTE,
    source: "https://www.just.edu.jo",
  },
  {
    key: "just-civil-engineering-bsc",
    uni: "just",
    name: bi("Civil Engineering BSc", "بكالوريوس الهندسة المدنية"),
    field: "engineering",
    degree: "BSc",
    years: 5,
    required: ["MATH", "PHYS"],
    recommended: [],
    req: { route: JORDAN_ROUTE, JORDAN_TAWJIHI: { average: 80, streams: ["SCIENTIFIC"] } },
    english: null,
    notes: JORDAN_NOTE,
    source: "https://www.just.edu.jo",
  },
  {
    key: "psut-computer-science-bsc",
    uni: "psut",
    name: bi("Computer Science BSc", "بكالوريوس علم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH"],
    recommended: [],
    req: {
      route: { via: "DIRECT", url: "https://www.psut.edu.jo" },
      JORDAN_TAWJIHI: { streams: ["SCIENTIFIC", "IT"] },
      BRITISH: { notesEn: "Foreign certificates are accepted after Ministry of Education equivalency.", notesAr: "تُقبل الشهادات الأجنبية بعد معادلتها من وزارة التربية والتعليم." },
    },
    english: null,
    notes: JORDAN_NOTE,
    source: "https://www.psut.edu.jo",
  },
  {
    key: "gju-mechanical-engineering-bsc",
    uni: "gju",
    name: bi("Mechanical and Maintenance Engineering BSc", "بكالوريوس الهندسة الميكانيكية والصيانة"),
    field: "engineering",
    degree: "BSc",
    years: 5,
    required: ["MATH", "PHYS"],
    recommended: [],
    req: { route: JORDAN_ROUTE, JORDAN_TAWJIHI: { average: 80, streams: ["SCIENTIFIC"] } },
    english: null,
    notes: bi(
      "Includes German language study and a year in Germany. For Jordanian students, the real cut-off average changes every year.",
      "يتضمن البرنامج دراسة اللغة الألمانية وسنة في ألمانيا. ويتغير معدل القبول الفعلي للطلبة الأردنيين كل عام.",
    ),
    source: "https://www.gju.edu.jo",
  },
  {
    key: "yarmouk-computer-science-bsc",
    uni: "yarmouk",
    name: bi("Computer Science BSc", "بكالوريوس علم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH"],
    recommended: [],
    req: { route: JORDAN_ROUTE, JORDAN_TAWJIHI: { streams: ["SCIENTIFIC", "IT"] } },
    english: null,
    notes: JORDAN_NOTE,
    source: "https://www.yu.edu.jo",
  },

  // ---------------- Canada ----------------
  {
    key: "uoft-computer-science-bsc",
    uni: "university_of_toronto",
    name: bi("Computer Science BSc (St. George)", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 4,
    required: ["MATH"],
    recommended: [],
    req: {
      route: { via: "OUAC", deadlines: [{ kind: "equal", month: 1, day: 15 }], url: "https://future.utoronto.ca/apply/" },
      BRITISH: { subjects: [{ code: "MATH" }] },
      IB: { hl: [{ code: "MATH" }] },
      AMERICAN: { ap: [{ code: "MATH" }], testPolicy: "OPTIONAL" },
    },
    english: { ielts: 6.5, ieltsMinBand: 6.0, toefl: 100 },
    source: "https://future.utoronto.ca/programs/computer-science-st-george/",
  },
  {
    key: "waterloo-computer-science-bcs",
    uni: "waterloo",
    name: bi("Computer Science BCS", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BSc",
    years: 5,
    required: ["MATH"],
    recommended: ["FURTHER_MATH"],
    req: {
      route: { via: "OUAC", deadlines: [{ kind: "equal", month: 2, day: 1 }], url: "https://uwaterloo.ca/future-students/" },
      BRITISH: { subjects: [{ code: "MATH" }] },
      IB: { hl: [{ code: "MATH" }] },
    },
    english: { ielts: 6.5, ieltsMinBand: 6.0, toefl: 90 },
    notes: bi("Co-op programme; the Admission Information Form is an important part of the application.", "برنامج تعليم تعاوني، ويُعد نموذج معلومات القبول جزءًا مهمًا من الطلب."),
    source: "https://uwaterloo.ca/future-students/programs/computer-science",
  },

  // ---------------- Australia ----------------
  {
    key: "unimelb-science-bsc",
    uni: "unimelb",
    name: bi("Bachelor of Science", "بكالوريوس العلوم"),
    field: "science",
    degree: "BSc",
    years: 3,
    required: ["MATH"],
    recommended: ["CHEM", "PHYS"],
    req: { route: { via: "DIRECT", url: "https://study.unimelb.edu.au/how-to-apply" }, BRITISH: { subjects: [{ code: "MATH" }] }, IB: { hl: [{ code: "MATH" }] } },
    english: { ielts: 6.5, ieltsMinBand: 6.0, toefl: 79 },
    source: "https://study.unimelb.edu.au/find/courses/undergraduate/bachelor-of-science/",
  },

  // ---------------- Europe ----------------
  {
    key: "tudelft-aerospace-bsc",
    uni: "tu_delft",
    name: bi("Aerospace Engineering BSc", "بكالوريوس هندسة الطيران والفضاء"),
    field: "engineering",
    degree: "BSc",
    years: 3,
    required: ["MATH", "PHYS"],
    recommended: [],
    req: {
      route: { via: "STUDIELINK", deadlines: [{ kind: "regular", month: 1, day: 15 }], url: "https://www.studielink.nl" },
      BRITISH: { subjects: [{ code: "MATH" }, { code: "PHYS" }] },
      IB: { hl: [{ code: "MATH" }, { code: "PHYS" }] },
    },
    english: { ielts: 6.5, ieltsMinBand: 6.0, toefl: 90 },
    notes: bi("Numerus fixus programme with a selection procedure.", "برنامج بعدد مقاعد محدود مع إجراءات اختيار."),
    source: "https://www.tudelft.nl/en/education/programmes/bachelors/ae/bachelor-of-aerospace-engineering",
  },
  {
    key: "uva-psychology-bsc",
    uni: "university_of_amsterdam",
    name: bi("Psychology BSc", "بكالوريوس علم النفس"),
    field: "psychology",
    degree: "BSc",
    years: 3,
    required: [],
    recommended: ["MATH"],
    req: { route: { via: "STUDIELINK", url: "https://www.studielink.nl" } },
    english: { ielts: 6.5, toefl: 92 },
    source: "https://www.uva.nl/en/programmes/bachelors/psychology/psychology.html",
  },
  {
    key: "tum-informatics-bsc",
    uni: "tu_munich",
    name: bi("Informatics BSc", "بكالوريوس المعلوماتية"),
    field: "computer_science",
    degree: "BSc",
    years: 3,
    required: ["MATH"],
    recommended: [],
    req: { route: { via: "DIRECT", url: "https://www.tum.de/en/studies/application" } },
    english: null,
    notes: bi("Taught mainly in German; a German language certificate and an aptitude assessment are usually required.", "يُدرَّس البرنامج غالبًا باللغة الألمانية، ويُطلب عادة إثبات إتقان الألمانية وتقييم للأهلية."),
    source: "https://www.tum.de/en/studies/degree-programs/detail/informatics-bachelor-of-science-bsc",
  },
  {
    key: "tcd-computer-science-ba",
    uni: "trinity_college_dublin",
    name: bi("Computer Science BA", "بكالوريوس علوم الحاسوب"),
    field: "computer_science",
    degree: "BA",
    years: 4,
    required: ["MATH"],
    recommended: [],
    req: { route: { via: "CAO", deadlines: [{ kind: "regular", month: 2, day: 1 }], url: "https://www.cao.ie" } },
    english: { ielts: 6.5, ieltsMinBand: 6.0 },
    notes: bi("EU applicants apply through the CAO; other applicants usually apply directly to Trinity.", "يتقدم طلاب الاتحاد الأوروبي عبر CAO، أما غيرهم فيتقدمون عادة مباشرة إلى الجامعة."),
    source: "https://www.tcd.ie/courses/undergraduate/courses/computer-science/",
  },
];
