// Suggested walkthrough steps per demo persona. Each step links to a real page.
export const GUIDE_STEPS: Record<string, Array<{ key: string; href: string }>> = {
  student: [
    { key: "assessment", href: "/career/assessment" },
    { key: "matches", href: "/career" },
    { key: "chooseSubjects", href: "/subjects" },
    { key: "myGrades", href: "/grades" },
    { key: "pathwayPlan", href: "/career/pathways" },
    { key: "pathwayWhatIf", href: "/career/pathways/what-if" },
    { key: "pathways", href: "/career/universities" },
    { key: "myApplications", href: "/career/applications" },
    { key: "bookAdvisor", href: "/services/career_guidance" },
    { key: "myRequests", href: "/requests" },
    { key: "tasks", href: "/tasks" },
    { key: "myTimetable", href: "/timetable" },
  ],
  parent: [
    { key: "children", href: "/children" },
    { key: "childSubjects", href: "/subjects" },
    { key: "childGrades", href: "/grades" },
    { key: "examTimetable", href: "/exams" },
    { key: "tripConsent", href: "/trips" },
    { key: "letter", href: "/services/document_request" },
    { key: "subjectChange", href: "/services/subject_change" },
    { key: "parentMeeting", href: "/services/parent_meeting" },
    { key: "documents", href: "/documents" },
    { key: "childTimetable", href: "/timetable" },
    { key: "pathwaysParent", href: "/career/universities/results" },
    { key: "childApplications", href: "/career/applications" },
    { key: "pathwayChild", href: "/career/pathways" },
  ],
  teacher: [
    { key: "gradebook", href: "/grades" },
    { key: "refer", href: "/services/academic_concern" },
    { key: "myClasses", href: "/classes" },
    { key: "approvals", href: "/approvals" },
    { key: "meetings", href: "/meetings" },
    { key: "safeguardingRefer", href: "/safeguarding" },
    { key: "teachingWeek", href: "/timetable" },
    { key: "lessonPlans", href: "/curriculum/plans" },
    { key: "curriculumGaps", href: "/curriculum" },
    { key: "tripBoard", href: "/trips" },
    { key: "letterRequests", href: "/career/applications/letters" },
  ],
  counselor: [
    { key: "caseload", href: "/cases" },
    { key: "pathwaysConfirm", href: "/career/universities/results" },
    { key: "applicationBoard", href: "/career/applications/manage" },
    { key: "catalogReview", href: "/career/catalog" },
    { key: "pathwayApprove", href: "/career/pathways?tab=awaiting" },
    { key: "pathwayDashboard", href: "/career/pathways/dashboard" },
    { key: "meetings", href: "/meetings" },
    { key: "calendar", href: "/calendar" },
    { key: "students", href: "/students" },
  ],
  career_advisor: [
    { key: "careerDesk", href: "/career" },
    { key: "pathwaysManage", href: "/career/universities/manage" },
    { key: "applicationBoard", href: "/career/applications/manage" },
    { key: "catalogReview", href: "/career/catalog" },
    { key: "pathwayPlanner", href: "/career/pathways" },
    { key: "transcriptReview", href: "/career/pathways/imports" },
    { key: "caseload", href: "/cases" },
    { key: "calendar", href: "/calendar" },
  ],
  dsl: [
    { key: "sgQueue", href: "/safeguarding" },
    { key: "caseload", href: "/cases" },
    { key: "audit", href: "/admin/audit" },
  ],
  deputy_dsl: [{ key: "sgQueue", href: "/safeguarding" }],
  principal: [
    { key: "kpis", href: "/home" },
    { key: "analytics", href: "/analytics" },
    { key: "gradesOverview", href: "/grades?view=overview" },
    { key: "approvals", href: "/approvals" },
    { key: "coverBoard", href: "/admin/cover" },
    { key: "curriculumGaps", href: "/curriculum" },
  ],
  admin: [
    { key: "servicesAdmin", href: "/admin/services" },
    { key: "formBuilder", href: "/admin/forms" },
    { key: "workflowBuilder", href: "/admin/workflows" },
    { key: "templates", href: "/admin/templates" },
    { key: "compliance", href: "/admin/compliance" },
    { key: "registration", href: "/admin/registration" },
    { key: "gradeBands", href: "/grades?view=bands" },
    { key: "timetableSetup", href: "/admin/timetable" },
    { key: "calendarAdmin", href: "/admin/calendar" },
    { key: "examsAdmin", href: "/admin/exams" },
  ],
  registrar: [
    { key: "approvals", href: "/approvals" },
    { key: "registration", href: "/admin/registration?tab=rosters" },
    { key: "documents", href: "/documents" },
    { key: "templates", href: "/admin/templates" },
    { key: "timetableSetup", href: "/admin/timetable" },
  ],
  hod_computing: [
    { key: "gradesOverview", href: "/grades?view=overview" },
    { key: "approvals", href: "/approvals" },
    { key: "requestsAll", href: "/requests?tab=all" },
    { key: "coverBoard", href: "/admin/cover" },
    { key: "planReview", href: "/curriculum/review" },
  ],
};
