"use client";

import {
  BarChart3,
  Blocks,
  Building2,
  Calendar,
  CalendarClock,
  CheckSquare,
  Compass,
  Contact,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FolderKanban,
  GraduationCap,
  Home,
  Inbox,
  LayoutGrid,
  ListChecks,
  Scale,
  ScrollText,
  Shield,
  Stamp,
  Users,
  Workflow,
  type LucideIcon,
  ArrowLeftRight,
  BookOpen,
  Brain,
  Briefcase,
  Bus,
  CalendarCheck,
  CalendarDays,
  CalendarX,
  ClipboardCheck,
  Clock,
  Flag,
  Heart,
  HeartHandshake,
  HeartPulse,
  IdCard,
  Laptop,
  Lock,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Monitor,
  Puzzle,
  School,
  ShieldAlert,
  Stethoscope,
  Trophy,
  Wrench,
  Landmark,
  Send,
  Gift,
  Settings,
  Share2,
} from "lucide-react";
import { DynamicIcon, type IconName } from "lucide-react/dynamic";

const STATIC: Record<string, LucideIcon> = {
  "bar-chart-3": BarChart3,
  blocks: Blocks,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  "check-square": CheckSquare,
  compass: Compass,
  contact: Contact,
  "file-signature": FileSignature,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "folder-kanban": FolderKanban,
  "graduation-cap": GraduationCap,
  home: Home,
  inbox: Inbox,
  "layout-grid": LayoutGrid,
  "list-checks": ListChecks,
  scale: Scale,
  "scroll-text": ScrollText,
  shield: Shield,
  stamp: Stamp,
  users: Users,
  workflow: Workflow,
  "arrow-left-right": ArrowLeftRight,
  "book-open": BookOpen,
  "brain": Brain,
  "briefcase": Briefcase,
  "bus": Bus,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "calendar-x": CalendarX,
  "clipboard-check": ClipboardCheck,
  "clock": Clock,
  "flag": Flag,
  "heart": Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  "id-card": IdCard,
  "laptop": Laptop,
  "lock": Lock,
  "mail": Mail,
  "map": Map,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "monitor": Monitor,
  "puzzle": Puzzle,
  "school": School,
  "landmark": Landmark,
  "send": Send,
  "shield-alert": ShieldAlert,
  "stethoscope": Stethoscope,
  "trophy": Trophy,
  "wrench": Wrench,
  gift: Gift,
  settings: Settings,
  "share-2": Share2,
};

/** Icon by kebab-case lucide name. Common icons are bundled; others load on demand. */
export function Icon({ name, className }: { name: string; className?: string }) {
  const Static = STATIC[name];
  if (Static) return <Static className={className} aria-hidden />;
  return <DynamicIcon name={name as IconName} className={className} aria-hidden fallback={() => <span className={className} />} />;
}
