// Permission keys and the system roles seeded into every organization.

export const PERMISSIONS = [
  "admin.access",
  "school.manage",
  "people.view",
  "people.manage",
  "people.invite",
  "roles.manage",
  "people.reveal_ids",
  "people.medical",
  "services.use",
  "services.manage",
  "forms.manage",
  "workflows.manage",
  "requests.view_all",
  "requests.process",
  "approvals.decide",
  "cases.view",
  "cases.view_all",
  "cases.manage",
  "cases.wellbeing",
  "safeguarding.refer",
  "safeguarding.view",
  "safeguarding.manage",
  "safeguarding.export",
  "safeguarding.break_glass",
  "tasks.use",
  "appointments.book",
  "appointments.host",
  "appointments.manage",
  "calendar.view",
  "documents.view",
  "documents.manage",
  "documents.sensitive",
  "documents.templates",
  "career.use",
  "career.advise",
  "analytics.view",
  "compliance.manage",
  "audit.view",
  "ai.use",
  "ai.admin_insights",
  "comms.send",
  "family.portal",
  "student.portal",
  "demo.reset",
  "grades.enter",
  "grades.view_all",
  "grades.view_own",
  "registration.submit",
  "registration.manage",
  "trips.manage",
  "trips.consent",
  "calendar.manage",
  "curriculum.plan",
  "curriculum.review",
  "curriculum.manage",
  "pathways.view",
  "pathways.manage",
  "planner.approve",
  "applications.manage",
  "catalog.review",
  "timetable.manage",
  "absence.report",
  "cover.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const STAFF_BASE: Permission[] = [
  "absence.report",
  "services.use",
  "people.view",
  "safeguarding.refer",
  "tasks.use",
  "appointments.book",
  "calendar.view",
  "documents.view",
  "ai.use",
  "comms.send",
  "cases.view",
];

export type RoleDefinition = {
  key: string;
  nameEn: string;
  nameAr: string;
  descEn: string;
  descAr: string;
  permissions: Permission[];
};

export const SYSTEM_ROLES: RoleDefinition[] = [
  {
    key: "school_admin",
    nameEn: "School Administrator",
    nameAr: "مسؤول المدرسة",
    descEn: "Runs school setup, services, forms, workflows and compliance.",
    descAr: "يدير إعدادات المدرسة والخدمات والنماذج ومسارات العمل والامتثال.",
    permissions: [
      "cover.manage",
      "timetable.manage",
      "grades.view_all",
      "registration.manage",
      "trips.manage",
      "calendar.manage",
      "curriculum.manage",
      "curriculum.review",
      "pathways.view",
      "pathways.manage",
      "applications.manage",
      "catalog.review",
      ...STAFF_BASE,
      "admin.access",
      "school.manage",
      "people.manage",
      "people.invite",
      "roles.manage",
      "people.reveal_ids",
      "services.manage",
      "forms.manage",
      "workflows.manage",
      "requests.view_all",
      "requests.process",
      "approvals.decide",
      "cases.view_all",
      "cases.manage",
      "appointments.host",
      "appointments.manage",
      "documents.manage",
      "documents.templates",
      "analytics.view",
      "compliance.manage",
      "audit.view",
      "ai.admin_insights",
      "demo.reset",
    ],
  },
  {
    key: "principal",
    nameEn: "Principal",
    nameAr: "مدير المدرسة",
    descEn:
      "School leadership with oversight of all operations. Access to safeguarding is audited.",
    descAr:
      "قيادة المدرسة مع الإشراف على جميع العمليات. الوصول إلى ملفات الحماية يخضع للتدقيق.",
    permissions: [
      "cover.manage",
      "timetable.manage",
      "grades.view_all",
      "registration.manage",
      "trips.manage",
      "calendar.manage",
      "curriculum.manage",
      "curriculum.review",
      "pathways.view",
      ...STAFF_BASE,
      "admin.access",
      "people.invite",
      "roles.manage",
      "requests.view_all",
      "approvals.decide",
      "cases.view_all",
      "cases.manage",
      "cases.wellbeing",
      "safeguarding.break_glass",
      "appointments.host",
      "documents.manage",
      "analytics.view",
      "audit.view",
      "ai.admin_insights",
      "demo.reset",
    ],
  },
  {
    key: "registrar",
    nameEn: "Registrar",
    nameAr: "المسجل",
    descEn: "Handles enrollment, records and official documents.",
    descAr: "يتولى التسجيل والسجلات والوثائق الرسمية.",
    permissions: [
      "cover.manage",
      "timetable.manage",
      "grades.view_all",
      "registration.manage",
      "calendar.manage",
      "pathways.view",
      ...STAFF_BASE,
      "people.manage",
      "people.reveal_ids",
      "requests.view_all",
      "requests.process",
      "approvals.decide",
      "documents.manage",
      "documents.templates",
    ],
  },
  {
    key: "department_head",
    nameEn: "Head of Department",
    nameAr: "رئيس القسم",
    descEn: "Leads a department and approves subject and curriculum requests.",
    descAr: "يقود القسم ويعتمد طلبات المواد والمناهج.",
    permissions: [
      "cover.manage",
      "grades.enter",
      "grades.view_all",
      "trips.manage",
      "curriculum.plan",
      "curriculum.review",
      "curriculum.manage",
      ...STAFF_BASE,
      "approvals.decide",
      "appointments.host",
      "cases.manage",
    ],
  },
  {
    key: "teacher",
    nameEn: "Teacher",
    nameAr: "معلم",
    descEn: "Teaches classes, refers students and meets parents.",
    descAr: "يدرّس الصفوف ويحيل الطلاب ويلتقي بأولياء الأمور.",
    permissions: [
      "grades.enter",
      "trips.manage",
      "curriculum.plan",
      ...STAFF_BASE,
      "approvals.decide",
      "appointments.host",
    ],
  },
  {
    key: "counselor",
    nameEn: "School Counselor",
    nameAr: "المرشد الطلابي",
    descEn:
      "Supports students academically and personally. Manages wellbeing cases.",
    descAr: "يدعم الطلاب أكاديميًا وشخصيًا ويدير حالات الرفاه.",
    permissions: [
      "pathways.manage",
      "planner.approve",
      "applications.manage",
      "catalog.review",
      "grades.view_all",
      "pathways.view",
      ...STAFF_BASE,
      "cases.manage",
      "cases.wellbeing",
      "requests.process",
      "approvals.decide",
      "appointments.host",
      "documents.sensitive",
      "career.advise",
      "analytics.view",
    ],
  },
  {
    key: "career_advisor",
    nameEn: "Career Advisor",
    nameAr: "مستشار التوجيه المهني",
    descEn: "Guides students on careers and university applications.",
    descAr: "يوجّه الطلاب في المسارات المهنية والقبول الجامعي.",
    permissions: [
      "grades.view_all",
      "pathways.view",
      "pathways.manage",
      "planner.approve",
      "applications.manage",
      "catalog.review",
      ...STAFF_BASE,
      "cases.manage",
      "career.advise",
      "appointments.host",
      "requests.process",
    ],
  },
  {
    key: "wellbeing_lead",
    nameEn: "Wellbeing Lead",
    nameAr: "مسؤول الرفاه",
    descEn: "Leads student wellbeing and receives confidential requests.",
    descAr: "يقود رفاه الطلاب ويستقبل الطلبات السرية.",
    permissions: [
      ...STAFF_BASE,
      "cases.manage",
      "cases.wellbeing",
      "appointments.host",
      "documents.sensitive",
    ],
  },
  {
    key: "dsl",
    nameEn: "Designated Safeguarding Lead",
    nameAr: "مسؤول حماية الطفل المعيّن",
    descEn: "Leads child protection. Sees and manages all safeguarding cases.",
    descAr: "يقود حماية الطفل ويطّلع على جميع حالات الحماية ويديرها.",
    permissions: [
      ...STAFF_BASE,
      "cases.manage",
      "cases.wellbeing",
      "safeguarding.view",
      "safeguarding.manage",
      "safeguarding.export",
      "appointments.host",
      "documents.sensitive",
      "audit.view",
    ],
  },
  {
    key: "deputy_dsl",
    nameEn: "Deputy Safeguarding Lead",
    nameAr: "نائب مسؤول حماية الطفل",
    descEn: "Supports the DSL and covers in their absence.",
    descAr: "يساند مسؤول الحماية وينوب عنه عند غيابه.",
    permissions: [
      ...STAFF_BASE,
      "cases.manage",
      "cases.wellbeing",
      "safeguarding.view",
      "safeguarding.manage",
      "appointments.host",
      "documents.sensitive",
    ],
  },
  {
    key: "nurse",
    nameEn: "School Nurse",
    nameAr: "ممرض المدرسة",
    descEn: "Manages medical records and health visits.",
    descAr: "يدير السجلات الطبية والزيارات الصحية.",
    permissions: [...STAFF_BASE, "people.medical", "appointments.host"],
  },
  {
    key: "it_support",
    nameEn: "IT Support",
    nameAr: "الدعم التقني",
    descEn: "Resolves IT requests.",
    descAr: "يعالج طلبات الدعم التقني.",
    permissions: [...STAFF_BASE, "requests.process"],
  },
  {
    key: "student",
    nameEn: "Student",
    nameAr: "طالب",
    descEn: "Uses services, books meetings and tracks requests.",
    descAr: "يستخدم الخدمات ويحجز المواعيد ويتابع الطلبات.",
    permissions: [
      "grades.view_own",
      "registration.submit",
      "pathways.view",
      "student.portal",
      "services.use",
      "tasks.use",
      "appointments.book",
      "calendar.view",
      "career.use",
      "documents.view",
      "ai.use",
    ],
  },
  {
    key: "parent",
    nameEn: "Parent",
    nameAr: "ولي أمر",
    descEn: "Follows their children, approves requests and meets staff.",
    descAr: "يتابع أبناءه ويعتمد الطلبات ويلتقي بالكادر.",
    permissions: [
      "grades.view_own",
      "registration.submit",
      "trips.consent",
      "pathways.view",
      "family.portal",
      "services.use",
      "approvals.decide",
      "appointments.book",
      "calendar.view",
      "documents.view",
      "ai.use",
    ],
  },
];

export const STAFF_ROLE_KEYS = SYSTEM_ROLES.map((r) => r.key).filter(
  (k) => k !== "student" && k !== "parent",
);
