// Fields of study (global) and which fields lead to each career in prisma/seed/data/careers.ts.
export type FieldSeed = { key: string; en: string; ar: string; cip: string[]; related: string[] };

export const FIELDS_OF_STUDY: FieldSeed[] = [
  { key: "computer_science", en: "Computer Science", ar: "علوم الحاسوب", cip: ["11.0701"], related: ["software_engineering", "artificial_intelligence", "data_science"] },
  { key: "artificial_intelligence", en: "Artificial Intelligence", ar: "الذكاء الاصطناعي", cip: ["11.0102"], related: ["computer_science", "data_science"] },
  { key: "data_science", en: "Data Science", ar: "علم البيانات", cip: ["30.7001"], related: ["computer_science", "mathematics", "statistics"] },
  { key: "software_engineering", en: "Software Engineering", ar: "هندسة البرمجيات", cip: ["14.0903"], related: ["computer_science", "computer_engineering"] },
  { key: "cybersecurity", en: "Cybersecurity", ar: "الأمن السيبراني", cip: ["11.1003"], related: ["computer_science"] },
  { key: "computer_engineering", en: "Computer Engineering", ar: "هندسة الحاسوب", cip: ["14.0901"], related: ["electrical_engineering", "computer_science"] },
  { key: "electrical_engineering", en: "Electrical and Electronic Engineering", ar: "الهندسة الكهربائية والإلكترونية", cip: ["14.1001"], related: ["computer_engineering"] },
  { key: "mechanical_engineering", en: "Mechanical Engineering", ar: "الهندسة الميكانيكية", cip: ["14.1901"], related: ["aerospace_engineering", "mechatronics"] },
  { key: "mechatronics", en: "Mechatronics and Robotics", ar: "الميكاترونكس والروبوتات", cip: ["15.0405"], related: ["mechanical_engineering", "electrical_engineering"] },
  { key: "civil_engineering", en: "Civil Engineering", ar: "الهندسة المدنية", cip: ["14.0801"], related: ["architecture"] },
  { key: "aerospace_engineering", en: "Aerospace Engineering", ar: "هندسة الطيران والفضاء", cip: ["14.0201"], related: ["mechanical_engineering"] },
  { key: "chemical_engineering", en: "Chemical Engineering", ar: "الهندسة الكيميائية", cip: ["14.0701"], related: ["chemistry"] },
  { key: "biomedical_engineering", en: "Biomedical Engineering", ar: "الهندسة الطبية الحيوية", cip: ["14.0501"], related: ["biomedical_science"] },
  { key: "energy_engineering", en: "Energy and Sustainable Engineering", ar: "هندسة الطاقة المستدامة", cip: ["14.0401"], related: ["environmental_science"] },
  { key: "medicine", en: "Medicine", ar: "الطب", cip: ["51.1201"], related: ["biomedical_science"] },
  { key: "dentistry", en: "Dentistry", ar: "طب الأسنان", cip: ["51.0401"], related: ["medicine"] },
  { key: "pharmacy", en: "Pharmacy", ar: "الصيدلة", cip: ["51.2001"], related: ["chemistry"] },
  { key: "nursing", en: "Nursing", ar: "التمريض", cip: ["51.3801"], related: ["medicine"] },
  { key: "physiotherapy", en: "Physiotherapy", ar: "العلاج الطبيعي", cip: ["51.2308"], related: ["sports_science"] },
  { key: "veterinary_medicine", en: "Veterinary Medicine", ar: "الطب البيطري", cip: ["51.2401"], related: ["biology"] },
  { key: "biomedical_science", en: "Biomedical Sciences", ar: "العلوم الطبية الحيوية", cip: ["26.0102"], related: ["biology", "medicine"] },
  { key: "biology", en: "Biology", ar: "الأحياء", cip: ["26.0101"], related: ["biomedical_science", "environmental_science"] },
  { key: "chemistry", en: "Chemistry", ar: "الكيمياء", cip: ["40.0501"], related: ["chemical_engineering", "pharmacy"] },
  { key: "physics", en: "Physics", ar: "الفيزياء", cip: ["40.0801"], related: ["mathematics"] },
  { key: "mathematics", en: "Mathematics", ar: "الرياضيات", cip: ["27.0101"], related: ["data_science", "physics"] },
  { key: "environmental_science", en: "Environmental Science", ar: "علوم البيئة", cip: ["03.0104"], related: ["biology"] },
  { key: "psychology", en: "Psychology", ar: "علم النفس", cip: ["42.0101"], related: ["education"] },
  { key: "law", en: "Law", ar: "القانون", cip: ["22.0101"], related: ["international_relations"] },
  { key: "business", en: "Business and Management", ar: "إدارة الأعمال", cip: ["52.0201"], related: ["finance", "marketing"] },
  { key: "economics", en: "Economics", ar: "الاقتصاد", cip: ["45.0601"], related: ["finance"] },
  { key: "finance", en: "Finance", ar: "التمويل", cip: ["52.0801"], related: ["economics", "accounting"] },
  { key: "accounting", en: "Accounting", ar: "المحاسبة", cip: ["52.0301"], related: ["finance"] },
  { key: "marketing", en: "Marketing", ar: "التسويق", cip: ["52.1401"], related: ["business", "media"] },
  { key: "architecture", en: "Architecture", ar: "العمارة", cip: ["04.0201"], related: ["urban_planning", "design"] },
  { key: "urban_planning", en: "Urban Planning", ar: "التخطيط الحضري", cip: ["04.0301"], related: ["architecture"] },
  { key: "design", en: "Design", ar: "التصميم", cip: ["50.0401"], related: ["media", "architecture"] },
  { key: "media", en: "Media and Communication", ar: "الإعلام والاتصال", cip: ["09.0102"], related: ["design"] },
  { key: "education", en: "Education", ar: "التربية والتعليم", cip: ["13.0101"], related: ["psychology"] },
  { key: "international_relations", en: "International Relations", ar: "العلاقات الدولية", cip: ["45.0901"], related: ["law", "economics"] },
  { key: "social_work", en: "Social Work", ar: "الخدمة الاجتماعية", cip: ["44.0701"], related: ["psychology"] },
  { key: "hospitality", en: "Hospitality and Tourism", ar: "الضيافة والسياحة", cip: ["52.0901"], related: ["business"] },
  { key: "sports_science", en: "Sports and Exercise Science", ar: "علوم الرياضة والتمارين", cip: ["31.0505"], related: ["physiotherapy"] },
  { key: "aviation", en: "Aviation", ar: "الطيران", cip: ["49.0102"], related: ["aerospace_engineering"] },
];

/** careerKey -> [fieldKey, weight 1 to 5]. Every career in careers.ts has at least one field. */
export const CAREER_FIELDS: Record<string, Array<[string, number]>> = {
  ai_engineer: [["artificial_intelligence", 5], ["computer_science", 5], ["data_science", 4], ["software_engineering", 3], ["computer_engineering", 3], ["mathematics", 2], ["electrical_engineering", 2]],
  software_developer: [["software_engineering", 5], ["computer_science", 5], ["computer_engineering", 3], ["artificial_intelligence", 2]],
  data_scientist: [["data_science", 5], ["computer_science", 4], ["mathematics", 4], ["artificial_intelligence", 3], ["economics", 2]],
  cybersecurity_analyst: [["cybersecurity", 5], ["computer_science", 4], ["computer_engineering", 3], ["software_engineering", 2]],
  robotics_engineer: [["mechatronics", 5], ["mechanical_engineering", 4], ["electrical_engineering", 4], ["computer_engineering", 3], ["artificial_intelligence", 2]],
  mechanical_engineer: [["mechanical_engineering", 5], ["aerospace_engineering", 3], ["mechatronics", 3]],
  civil_engineer: [["civil_engineering", 5], ["architecture", 2], ["urban_planning", 2]],
  electrical_engineer: [["electrical_engineering", 5], ["computer_engineering", 4], ["energy_engineering", 3]],
  aerospace_engineer: [["aerospace_engineering", 5], ["mechanical_engineering", 4], ["physics", 2]],
  architect: [["architecture", 5], ["urban_planning", 3], ["design", 3], ["civil_engineering", 2]],
  doctor: [["medicine", 5], ["biomedical_science", 3]],
  pharmacist: [["pharmacy", 5], ["chemistry", 3], ["biomedical_science", 2]],
  nurse: [["nursing", 5], ["biomedical_science", 2]],
  dentist: [["dentistry", 5], ["medicine", 2]],
  physiotherapist: [["physiotherapy", 5], ["sports_science", 3]],
  psychologist: [["psychology", 5], ["social_work", 2]],
  veterinarian: [["veterinary_medicine", 5], ["biology", 3]],
  biomedical_scientist: [["biomedical_science", 5], ["biology", 4], ["biomedical_engineering", 3], ["chemistry", 2]],
  environmental_scientist: [["environmental_science", 5], ["biology", 3], ["energy_engineering", 2]],
  marine_biologist: [["biology", 5], ["environmental_science", 4]],
  chemist: [["chemistry", 5], ["chemical_engineering", 3], ["pharmacy", 2]],
  accountant: [["accounting", 5], ["finance", 4], ["business", 3]],
  financial_analyst: [["finance", 5], ["economics", 4], ["accounting", 3], ["mathematics", 2]],
  entrepreneur: [["business", 5], ["economics", 3], ["marketing", 3], ["computer_science", 2]],
  marketing_manager: [["marketing", 5], ["business", 4], ["media", 3]],
  supply_chain_manager: [["business", 5], ["economics", 3], ["mechanical_engineering", 1]],
  economist: [["economics", 5], ["finance", 3], ["mathematics", 3], ["international_relations", 2]],
  graphic_designer: [["design", 5], ["media", 3]],
  ux_designer: [["design", 5], ["computer_science", 3], ["psychology", 2]],
  game_designer: [["design", 4], ["computer_science", 4], ["software_engineering", 3], ["media", 2]],
  film_producer: [["media", 5], ["design", 2]],
  journalist: [["media", 5], ["international_relations", 2]],
  interior_designer: [["design", 5], ["architecture", 4]],
  fashion_designer: [["design", 5], ["marketing", 2]],
  teacher: [["education", 5], ["psychology", 2]],
  school_counselor: [["psychology", 5], ["education", 4], ["social_work", 3]],
  social_worker: [["social_work", 5], ["psychology", 4]],
  lawyer: [["law", 5], ["international_relations", 2]],
  diplomat: [["international_relations", 5], ["law", 3], ["economics", 3]],
  urban_planner: [["urban_planning", 5], ["architecture", 3], ["civil_engineering", 3]],
  pilot: [["aviation", 5], ["aerospace_engineering", 3]],
  hospitality_manager: [["hospitality", 5], ["business", 3]],
  event_manager: [["hospitality", 4], ["marketing", 4], ["business", 3]],
  renewable_energy_engineer: [["energy_engineering", 5], ["electrical_engineering", 4], ["mechanical_engineering", 3], ["environmental_science", 2]],
  sustainability_consultant: [["environmental_science", 5], ["energy_engineering", 3], ["business", 3], ["economics", 2]],
  sports_scientist: [["sports_science", 5], ["physiotherapy", 3], ["biology", 2]],
  sports_coach: [["sports_science", 5], ["education", 3]],
};
