// Turns validated research output into the official catalog data the seed loads.
// Only batches that pass scripts/research/validate.mjs with zero errors are accepted. Each source gets
// the retrieval date and content hash of the page text that its quotes were checked against.
//
// Usage: node scripts/research/assemble.mjs --out-dir <research out folder> --pages <decrypted pages folder>
// Writes prisma/seed/catalog/official/<batch>.json and prisma/seed/catalog/official/index.ts
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, v, i, all) => (v.startsWith("--") ? [...acc, [v.slice(2), all[i + 1]]] : acc), []),
);
const target = "prisma/seed/catalog/official";
mkdirSync(target, { recursive: true });
const index = JSON.parse(readFileSync(join(args.pages, "index.json"), "utf8"));
const batches = [];
for (const f of readdirSync(args["out-dir"]).filter((x) => x.endsWith(".json")).sort()) {
  const file = join(args["out-dir"], f);
  try {
    execFileSync("node", ["scripts/research/validate.mjs", "--data", file, "--pages", args.pages], { stdio: "pipe" });
  } catch (e) {
    const out = String(e.stdout ?? "");
    console.log(`SKIP ${f}: validation failed (${(out.match(/^ERROR/gm) ?? []).length} errors)`);
    continue;
  }
  const data = JSON.parse(readFileSync(file, "utf8"));
  for (const u of data.universities ?? []) {
    for (const s of u.sources ?? []) {
      const e = index[s.url];
      if (!e) continue;
      s.retrievedAt = e.fetchedAt;
      s.hash = e.hash;
      if (e.via) s.via = e.via;
      if (e.wayback) {
        s.waybackTimestamp = e.wayback.timestamp;
        s.waybackHash = e.wayback.hash;
      }
    }
  }
  const batch = data.batch ?? f.replace(/\.json$/, "");
  writeFileSync(join(target, `${batch}.json`), JSON.stringify({ batch, assembledAt: new Date().toISOString(), universities: data.universities ?? [] }, null, 1));
  batches.push(batch);
  console.log(`OK   ${f}: ${(data.universities ?? []).length} universities`);
}
const ids = batches.map((b) => b.replace(/[^a-zA-Z0-9]/g, "_"));
writeFileSync(
  join(target, "index.ts"),
  [
    "// Generated by scripts/research/assemble.mjs. Official entry requirements, validated against the fetched pages.",
    'import type { OfficialBatch } from "../official";',
    ...batches.map((b, i) => `import ${ids[i]} from "./${b}.json";`),
    "",
    `export const OFFICIAL_BATCHES: OfficialBatch[] = [${ids.map((i) => `${i} as OfficialBatch`).join(", ")}];`,
    "",
  ].join("\n"),
);
console.log(`${batches.length} batches written to ${target}`);
